# Copyright (c) 2025 Eclipse Foundation

name: CI to run SEC on RTL changes

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'rtl/**'

jobs:
  sec:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # From https://github.com/marketplace/actions/setup-oss-cad-suite
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FuseSoC from lowRISC
        run: |
          python3 -m venv venv_cve2/
          source venv_cve2/bin/activate
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r python-requirements.txt
          # Make the venv tools available to subsequent steps
          echo "$PWD/venv_cve2/bin" >> $GITHUB_PATH

      - name: Check FuseSoC version
        run: |
          echo "which fusesoc: $(which fusesoc || true)"
          fusesoc --version || echo "fusesoc not found or failed to run"

      - name: Install OSS CAD Suite
        uses: YosysHQ/setup-oss-cad-suite@v3

      - name: Check Yosys version
        run: yosys --version || true

      - name: Run SEC on the standard core configuration
        run: make sec

      - name: Run SEC on the eXtension InterFace configuration
        run: make sec_Xinterface
